# Generated by Django 5.0.3 on 2024-08-14 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '部落格', 'verbose_name_plural': '部落格'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': '文章分類', 'verbose_name_plural': '文章分類'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': '評論', 'verbose_name_plural': '評論'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_time',
            field=models.DateTimeField(auto_now=True, verbose_name='發布時間'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='分類名稱'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='所屬部落格'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.TextField(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='發布時間'),
        ),
    ]
