name: Deploy Django to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django gunicorn

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.ec2-46-51-233-6.ap-northeast-1.compute.amazonaws.com }}
        EC2_USER: ${{ secrets.ubuntu }}
        EC2_KEY: ${{ secrets.aws-tokyo-djangoblog.pem }}
      run: |
        scp -i $aws-tokyo-djangoblog.pem -r . $ubuntu@$ec2-46-51-233-6.ap-northeast-1.compute.amazonaws.com:~/mydjangoapp
        ssh -i $aws-tokyo-djangoblog.pem $ubuntu@$ec2-46-51-233-6.ap-northeast-1.compute.amazonaws.com << 'EOF'
          cd ~/mydjangoapp
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
