name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH Key
      run: echo "$EC2_KEY" > ~/.ssh/id_rsa

    - name: Set SSH Key Permissions
      run: chmod 600 ~/.ssh/id_rsa

    - name: Skip host key checking
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

    - name: Deploy application
      run: |
        scp -i ~/.ssh/id_rsa -r . $EC2_USER@$EC2_HOST:~/mydjangoapp
        ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
          cd ~/mydjangoapp
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
